# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.wp:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        container_name: laravel-wordpress
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8085:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks: 
             - wordpress-network

networks:
  wordpress-network:
    name: wordpress-network
    driver: bridge
# volumes:
#     sail-mysql:
#         driver: local
#     sail-redis:
#         driver: local
#     sail-meilisearch:
#         driver: local
